apiVersion: v1
kind: Secret
metadata:
  name: nihongo-backend-secret
  labels:
    app: nihongo-backend
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://<neon-host>/<database>?sslmode=require"
  DB_USERNAME: "<neon-username>"
  DB_PASSWORD: "<neon-password>"
  JWT_SECRET: "<jwt-secret-at-least-32-characters>"
  OPENAI_API_KEY: "<openai-api-key>"
  GEMINI_API_KEY: "<gemini-api-key>"
